installer:
  release: "v0.4.28"
  image: "quay.io/devtron/inception"
  tag: "c62d4c30-185-9354"
  
components:
  dashboard:
    image: "quay.io/devtron/dashboard:607f522d-325-9604"
  devtron:
    image: "quay.io/devtron/hyperion:d9d2f924-280-9888"
    cicdImage: "quay.io/devtron/devtron:d9d2f924-326-9885"
  argocdDexServer:
    image: "quay.io/dexidp/dex:v2.25.0"
    initContainer:
      authenticator: "quay.io/devtron/authenticator:415f5470-279-6520"
      cicdAuthenticator: "quay.io/argoproj/argocd:v1.8.1"
  kubelink:
    image: "quay.io/devtron/kubelink:59a0df88-318-9226"
  postgres:
    image: "quay.io/devtron/postgres:11.9.0-debian-10-r26"
  
  migrator:
    image: "quay.io/devtron/migrator:6687f572-133-2208"
    envVars:
      devtron:
        GIT_BRANCH: "main"
        GIT_HASH: "d9d2f9243d23b38f349b54b772a5e7aed3e000f4"
      casbin:
        GIT_BRANCH: "main"
        GIT_HASH: "d9d2f9243d23b38f349b54b772a5e7aed3e000f4"
